project:
  type: book
  output-dir: docs

book:
  title: "Personal Notes"
  author: "Ryan Kingery"
  # date: "2/12/2023"
  page-navigation: true
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "Classical Mechanics" # classical-mechanics/classical-mechanics.qmd
      chapters:
        - classical-mechanics/newtonian-mechanics.qmd
        - classical-mechanics/simple-systems.qmd
        - classical-mechanics/reference-frames.qmd
        - classical-mechanics/lagrangian-mechanics.qmd
        - classical-mechanics/hamiltonian-mechanics.qmd
        - classical-mechanics/central-forces.qmd
        - classical-mechanics/coupled-oscillations.qmd
        - classical-mechanics/rigid-bodies.qmd
        - classical-mechanics/canonical-transformations.qmd
        - classical-mechanics/integrability-and-chaos.qmd
        - classical-mechanics/continuum-mechanics.qmd
    - part: "Electrodynamics" #electrodynamics/electrodynamics.qmd
      chapters:
        - electrodynamics/introduction.qmd
        - electrodynamics/electrostatics.qmd
    - part: "Circuit Analysis" # circuits/circuits.qmd
      chapters:
        - circuits/circuit-abstraction.qmd
        - circuits/analysis.qmd
        - circuits/nonlinear-methods.qmd
        - circuits/digital-abstraction.qmd
        - circuits/amplifiers.qmd
        - circuits/first-order-systems.qmd
        - circuits/second-order-systems.qmd
        - circuits/ac-analysis.qmd
        - circuits/op-amps.qmd
        - circuits/energy-power.qmd
    - part: "Quantum Mechanics" # quantum-mechanics/quantum-mechanics.qmd
      chapters:
        - quantum-mechanics/identical-particles.qmd
        - quantum-mechanics/second-quantization.qmd
    - part: "Statistical Mechanics" # statistical-mechanics/statistical-mechanics.qmd
      chapters:
        - tmp.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    toc-location: right
    toc-depth: 2
    number-sections: false
    fig-align: center
  pdf:
    documentclass: scrreprt



