project:
  type: book

book:
  title: "Course Notes"
  author: "Ryan Kingery"
  # date: "2/12/2023"
  chapters:
    - index.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



