# Electromagnetic Induction

Thus far we've spent a considerable amount of time studying *statics*, focusing on fields that are time-independent. We will now begin turning our attention to *dynamics*, where we allow the fields to depend explicitly on time. This leads us into the subject of *electrodynamics*, which we will study in depth for the rest of the course. To begin our study of this topic we will discuss a few important concepts that will lead us in the next chapter to Maxwell's equations, the crown jewel of electromagnetism. In this chapter, we'll start moving in this direction by discussing things like Ohm's law, electromotive force, Faraday's law, and electromagnetic induction.

## Ohm's Law

When a material is brought into contact with external electromagnetic fields, these fields will cause any unbound electrons inside the material to move in response to the fields, creating an induced current inside the material. If a material is placed in the vicinity of an external E-field $\mathbf{E}$ and an external B-field $\mathbf{B}$, there will be an induced current density $\mathbf{J} = \mathbf{J}(\mathbf{E},\mathbf{B})$ that's some function of these fields. Assuming the material is in electrostatic equilibrium before these fields are turned on, we can Taylor expand $\mathbf{J}$ to get a power series in $\mathbf{E}$. The $j$<sup>th</sup> component of the current density can then be written
$$
J_i = \sigma_{ij}(\mathbf{B}) E_i + \sigma_{ijk}(\mathbf{B}) E_j E_k + \cdots \ ,
$$
where the coefficients are some function of $\mathbf{B}$. If the applied E-field is sufficiently weak we can truncate to leading order to get
$$
J_i \approx \sigma_{ij}(\mathbf{B}) E_i \ .
$$
The coefficients $\sigma_{ij}(\mathbf{B})$ together form a $3 \times 3$ matrix, called the *conductivity matrix*. In general this matrix can be arbitrarily complicated. In the special case that the material is macroscopically *isotropic*, or uniform, and if $\mathbf{B} = \mathbf{0}$, this matrix becomes diagonal with $\sigma_{ij} = \sigma \delta_{ij}$, where $\sigma$ is some scalar constant. When this is true we get one version of *Ohm's Law*,
$$
\boxed{
\mathbf{J} = \sigma \mathbf{E}
} \ .
$$
The scalar $\sigma$ is an empirical constant that depends on the material. It's known as the electrical *conductivity*. As the name suggests, it's a measure of how much a given material is able to conduct current in response to an external E-field. It's precisely materials with a very high conductivity that we call conductors, since in a good conductor we expect that the smallest applied E-field would create the highest induced current. Materials with low conductivity are similarly called insulators, since in a good insulator we expect that a large applied E-field is needed to produce even the slightest amount of induced current. A perfect conductor would have an infinite, meaning *any* non-zero E-field would produce an infinitely high induced current, while a perfect insulator would have a zero conductivity, meaning no amount of E-field would produce an induced current.

In applied settings, one commonly defines $\rho \equiv 1/\sigma$, which is called the electrical *resistivity* of the material. In this case Ohm's law takes the form $\rho \mathbf{J} = \mathbf{E}$. Be careful not to confuse $\rho$ in this case with the charge density, as unfortunately the same notation is commonly used for both. Materials with low resistivity make good conductors, while those with high resistivity make good insulators. A perfect conductor would have a zero resistivity, while a perfect insulator has an infinite resistivity.

In Gaussian units, dimensional analysis requires that conductivity have dimensions of inverse time. This means that resistivity must have dimensions of time, or units of seconds in Gaussian units. In SI units, resistivity is typically given in units of Ohm-meters, or $\Omega \cdot \text{m}$, with $1 \ \Omega \cdot \text{m} \approx 10^{-10} \ \text{s}$. One Ohm is defined to be one volt per amp, and is a measure of electrical *resistance*, a related quantity we'll come back to below.

Most tables of materials list a material's resistivity rather than its conductivity, which is just the reciprocal of resistivity. Real life materials of course are neither perfect insulators nor perfect conductors, but many materials can be approximated as such. For example, good conductors like copper, gold, silver, and aluminum have resistivities of $\rho \sim 10^{-8} \ \Omega \cdot \text{m}$ or $\rho \sim 10^{-18} \ \text{s}$. Meanwhile, good insulators like quartz, glass, or wood have resistivities in the range $\rho \sim 10^{8} - 10^{16} \ \Omega \cdot \text{m}$ or $\rho \sim 10^{-2} - 10^{6} \ \text{s}$.

Notice from Ohm's law that as long as we have a steady current there can be no charge buildup anywhere inside the material. Indeed, since $\nabla \cdot \mathbf{J} = 0$ for steady currents and $\nabla \cdot \mathbf{E} = 4\pi\rho$, by Ohm's law we must have
$$
\rho = \frac{1}{4\pi} \nabla \cdot \mathbf{E} = \frac{1}{4\pi\sigma} \nabla \cdot \mathbf{J} = 0 \ .
$$
This means inside an Ohmic material with steady current we can assume $\rho = 0$ inside the material. This then means that the inside of the material satisfies Laplace's equation $\nabla^2 \phi = 0$, which means all the tools we derived before can be used to find the potential and E-field inside the material. On the surface, however, things are much more complicated since any excess free charge must accumulate on the surface of the material.

### V = IR

- Redo this section. Focus on isotropic materials hooked up to electrodes held at constant voltages.

Of course, the version of Ohm's law given above isn't the one most of us are probably familiar with. We're used to seeing Ohm's law in terms of voltage and current, not E-field and current density. To see how we get the more familiar version of Ohm's law, suppose …



the material in question is a wire with cross-sectional area $A$ and length $L$. If the applied E-field is approximately constant and directed along the wire, the potential difference $V$ across the wire is approximately
$$
V = \int_0^d \mathbf{E} \cdot d\boldsymbol{\ell} \approx |\mathbf{E}| L \ .
$$
Moreover, assuming the induced current $I$ running through the wire is approximately uniform, we have
$$
I = \int \mathbf{J} \cdot d\mathbf{a} \approx |\mathbf{J}| A \ .
$$
Plugging these expressions into Ohm's law above and multiplying both sides by $L/\sigma$, we have
$$
V = \frac{L}{\sigma A} I \ .
$$
The proportionality constant $R \equiv \sigma A/L$ we recognize as the electrical *resistance*. We thus have the familiar form of Ohm's law,
$$
\boxed{
V = IR
} \ .
$$
Evidently, the resistance is a function of *both* the conductivity properties of the material as well as its geometry. The greater the conductivity of the wire or the greater its cross-sectional area, the lower its resistance. The longer the wire is, the higher its resistance. For this reason, it doesn't make sense to take about the resistance of a material. It only makes sense to take about the resistance of a given *piece* of material, for example a piece of wire.

In Gaussian units, resistance has dimensions of time over distance, or units of $\text{s}/\text{cm}$. In SI units, resistance has units of volts per amp, which is commonly called an *Ohm*, denoted $\Omega$, with $1 \ \Omega \approx 10^{-12} \ \text{s}/\text{cm}$. As an example, a copper wire with a length of $1 \ \text{m}$ and a cross-sectional area of $1 \ \text{mm}$ would have a resistance of $R \approx 10^{-2} \ \Omega$ or $R \approx 10^{-14} \ \text{s}/\text{cm}$. A glass tube with the same length and cross-sectional area would have a much higher resistance of $R \approx 10^{14} \ \Omega$ or $R \approx 100 \ \text{s}/\text{cm}$.

### Drude Model

Ohm's law is a phenomenological law, meaning it's a relation that happens to sometimes hold for some materials. It's not a fundamental law of physics. It's thus fair to ask whether we can derive Ohm's law from more fundamental physics. To do this properly we will need to cover a little bit of solid state physics first. 

Strictly speaking, one should use quantum mechanics to truly understand the properties of solids, but it turns out we can get away with deriving Ohm's law from a purely classical theory of solids. This is known as the *Drude model* of a solid. The idea is to model a solid as an imperfect lattice of stationary atoms, or *defects*, along with a classical gas of free electrons that are allowed to flow freely throughout the solid. The free electrons are allowed to scatter with the defects and respond to an external field.

More formally, we make the following assumptions in Drude model:

1. The free electrons are allowed to scatter with defects according to a Poisson process. Suppose $\tau$ is the average time between collisions. It's an empirically measured constant that depends on the solid, known as the *mean free time*. We require that in any infinitesimal time interval $dt$, the probability of an electron scattering with a defect be a uniform value $dt/\tau$.
2. Once an electron scatters with a defect, we assume it immediately comes to rest with velocity $\mathbf{v} = \mathbf{0}$.
3. In between scattering events, the free electrons can only interact *classically* with an external applied force field $\mathbf{F}$. 
4. The electrons do not interact with each other at all.

Suppose an electron is moving through the solid with velocity $\mathbf{v}(t)$. We want to know what the velocity will be at an infinitesimally later time $t+dt$. But this velocity will depend on whether or not the electron scatters in the time interval $[t,t+dt]$. If the electron *does* scatter, by assumption (2) we must have $\mathbf{v}_{\text{scat}}(t+dt) = \mathbf{0}$.

By assumption (3), if the electron *does not* scatter in the time interval $[t,t+dt]$, its motion in this time interval will be given by Newton's second law. If $\mathbf{v}_{\text{no}}(t+dt)$ is the velocity when there is no scattering, we'd have
$$
m_e \frac{d}{dt} \mathbf{v}_{\text{no}}(t+dt) = \mathbf{F} \ .
$$
If we multiply both sides by $dt/m_e$ and write $d\mathbf{v}(t+dt) = \mathbf{v}(t+dt) - \mathbf{v}(t)$, we then get
$$
\mathbf{v}_{\text{no}}(t+dt) = \mathbf{v}(t) + \frac{\mathbf{F}}{m_e}dt \ .
$$
Now, what we'd like to know is the *expected*, or average, velocity $\langle\mathbf{v}\rangle$ of all the free electrons, not the velocity of any single electron. At time $t$ we assume $\mathbf{v}(t)$ is known, which means $\langle\mathbf{v}(t)\rangle = \mathbf{v}(t)$ exactly. At time $t+dt$ the expected velocity will be the weighted average of $\mathbf{v}_{\text{scat}}(t+dt)$ and $\mathbf{v}_{\text{no}}(t+dt)$, where the weights are the probability each possibility occurs,
$$
\langle \mathbf{v}(t+dt) \rangle = p_{\text{scat}} \mathbf{v}_{\text{scat}}(t+dt) + p_{\text{no}} \mathbf{v}_{\text{no}}(t+dt) \ .
$$
By assumption (1), we have $p_{\text{scat}} = dt/\tau$, ,which means $p_{\text{no}} = 1-dt/\tau$. We thus have
$$
\langle \mathbf{v}(t+dt) \rangle = \frac{dt}{\tau} \mathbf{0} + \bigg(1 - \frac{dt}{\tau}\bigg) \bigg[\mathbf{v}(t) + \frac{\mathbf{F}}{m_e} dt\bigg] \ .
$$
Assuming we know the velocity at time $t$, the expected velocity at time $t$ is just $\langle\mathbf{v}(t)\rangle = \mathbf{v}(t)$. If we now move $\mathbf{v}(t)$ to the left-hand side, drop any terms of order $dt^2$ on the right-hand side, and divide through by $dt$, we get
$$
\frac{\langle \mathbf{v}(t+dt) \rangle - \langle \mathbf{v}(t) \rangle}{dt} = \frac{\mathbf{F}}{m_e} - \frac{\langle\mathbf{v}(t)\rangle}{\tau} \ .
$$
Since $dt$ is infinitesimal, the left-hand side is just the time derivative $d\langle \mathbf{v} \rangle/dt$. We'll now drop the brackets from $\mathbf{v}$ since we won't need them anymore, in which case we can write
$$
\frac{d \mathbf{v}}{dt} = \frac{\mathbf{F}}{m_e} - \frac{\mathbf{v}}{\tau} \ .
$$
Now, in principle the applied force could be any force field. If the field is purely electromagnetic, the force is given by the Lorentz force law, in which case we'd have

$$
\frac{d \mathbf{v}}{dt} = -\frac{e}{m_e}\bigg[\mathbf{E} + \frac{\mathbf{v}}{c} \times \mathbf{B}\bigg] - \frac{\mathbf{v}}{\tau} \ .
$$
Note the minus sign on the charge, since electrons are negatively charged with $q=-e$. We now need to figure out what the current density is. If we suppose there are on average $n$ free electrons per unit volume inside the solid, then the electrons will have a uniform charge density $\rho = -en$, which means there will be a current density
$$
\mathbf{J} = \rho \mathbf{v} = -ne\mathbf{v} \ .
$$
Substituting this into the differential equation, we get
$$
\boxed{
\frac{d \mathbf{J}}{dt} = -\frac{ne^2}{m_e}\mathbf{E} + \frac{e}{m_ec} \mathbf{J} \times \mathbf{B} - \frac{\mathbf{J}}{\tau} 
} \ .
$$
This differential equation is known as the *generalized Ohm's law*. In principle it describes how the current density responds to the external electromagnetic fields at any point in time. On the right-hand side, we have a driving term plus a relaxation term $-\mathbf{J}/\tau$. 

In practice we don't really care about the transient behavior of the current, only its steady state behavior. One major reason for this is that the transient behavior dies off fast, on time scales of $\tau$. For pretty much all solids $\tau$ is very tiny. For example, many metals have relaxation times of order $\tau \sim 10^{-14} \ \text{s}$. This means a steady state current is reached almost instantly.

At steady state we can set $d\mathbf{J}/dt = \mathbf{0}$, which means the generalized Ohm's law reduces to
$$
\mathbf{0} = -\frac{ne^2}{m_e}\mathbf{E} + \frac{e}{m_ec} \mathbf{J} \times \mathbf{B} - \frac{\mathbf{J}}{\tau} \ .
$$
At this point it will be more convenient to solve for $\mathbf{E}$, in which case we get
$$
\mathbf{E} = \frac{m_e}{ne^2 \tau} \mathbf{J} + \frac{1}{nec} \mathbf{J} \times \mathbf{B} \ .
$$
Notice that this equation is linear in $\mathbf{J}$, which means the right-hand side must be some matrix multiple of $\mathbf{J}$. We'll call this matrix the *resistivity matrix* $\boldsymbol{\rho}$. It's not hard to show that the resistivity matrix can be written
$$
\boldsymbol{\rho} \equiv \begin{pmatrix}
m_e / ne^2 \tau & B_z / nec & -B_y / nec \\
-B_z / nec & m_e / ne^2 \tau & B_x / nec \\
B_y / nec & -B_x / nec & m_e / ne^2 \tau
\end{pmatrix} \ .
$$
This matrix will generally be invertible, in which case we can define a conductivity matrix $\boldsymbol{\sigma}$ as the matrix inverse of $\boldsymbol{\rho}$. We can then express the components of the current density in terms of the components of the E-field as
$$
J_i = \sigma_{ij} E_j \ .
$$
This is exactly what we wrote down at the beginning of the section. In the special case where $\mathbf{B} = \mathbf{0}$, the conductivity matrix becomes diagonal with $\sigma_{ij} = ne^2\tau/m_e \ \delta_{ij}$. Evidently, the conductivity $\sigma$ is given by
$$
\sigma = \frac{ne^2 \tau}{m_e} \ .
$$
Plugging this in, we finally arrive at Ohm's law, which is what we sought to derive,
$$
\mathbf{J} = \sigma \mathbf{E} \ .
$$
This derived expression for $\sigma$ hopefully makes sense. After all, the more free electrons there are, the higher $n$ will be, and thus the higher $\sigma$ will be. The longer the time between collisions, the faster the free electrons can move, which means $\sigma$ will be higher.

In this setting, one sometimes defines $\omega_p^2 \equiv 4\pi ne^2/m_e$, where $\omega_p$ is called the *plasma frequency*. The plasma frequency is a measure of the natural frequency of oscillations of electrons inside the electron gas. In terms of the plasma frequency, the conductivity is given by $\sigma = \tau\omega_p^2 / 4\pi$. Thus, the higher the plasma frequency, the higher the conductivity will be.

We can also use the Drude model to ask how to estimate how fast the free electrons are moving through the solid in response to the applied E-field. Since $\mathbf{J} = -ne\mathbf{v}$ and $\sigma = ne^2\tau / m_e$, the average velocity of these electrons at steady state will evidently be
$$
\mathbf{v} = -\frac{e\tau}{m_e} \mathbf{E} \ .
$$
Notice that, on average, the free electrons flow in the direction *opposite* the direction of the applied E-field, as we'd expect since electrons are negatively charged. Their average *speed* $v_d \equiv |\mathbf{v}|$ is known as the *drift velocity*, which is evidently
$$
v_d = \frac{e\tau}{m_e} |\mathbf{E}| \ .
$$
It's worth plugging in some numbers to get a feel for how fast this drift velocity is in a typical scenario. Supposing we apply an E-field of strength $|\mathbf{E}| = 1 \ \text{V}/\text{m}$ across a piece of copper with a mean free time of $\tau \approx 3 \cdot 10^{-14} \ \text{s}$, we'd have $v_d \approx 0.5 \ \text{cm}/\text{s}$. Thus, the free electrons are responding to the E-field very slowly. This is primarily due to all the collisions taking place as they move through the solid. These collisions cause the electrons to move through the material in a random walk, but with a slight drift in the direction of the E-field. The random walk velocities will average to zero, leaving only this tiny drift velocity to contribute to the average. Yet, this tiny drift velocity alone is entirely responsible for any induced currents measured in the material.

Since we derived the generalized Ohm's law assuming a B-field might also be present, it's worth briefly asking what happens in that case.  If $\mathbf{B} \neq \mathbf{0}$, the resistivity matrix won't be diagonal, and the off-diagonal terms will be a function of $\mathbf{B}$. This will cause the induced current to be deflected by the B-field away from its usual trajectory. For example, if the E-field is oriented in the $x$-direction, there will now be a component of current that moves along the $y$ and $z$ directions as well. This is known as the *Hall effect*. We can actually use the Hall effect to build a sensor to measure B-field strength. The idea is to use a material whose conductivity is known, apply a known voltage across the material (which gives $\mathbf{E}$), and use these to measure $\mathbf{B}$. These kinds of sensors are known as *Hall sensors*, and are commonly used nowadays to measure B-field strength.

### Ohmic Heating

The presence of a relaxation or drag term in the generalized Ohm's law above necessarily means that energy is being dissipated through the material as heat. After all, drag is not a conservative force, which means energy is not conserved unless thermal heat also gets taken into account. Fundamentally the heat loss is due to the random collisions, which causes the free electrons to lose kinetic energy, which gets converted into thermal energy and causes the material to warm up. This is known as *Ohmic heating*.

In fact, Ohmic heating must occur anytime there is a steady current being pumped through the material, whether the material obey's Ohm's law or not. To see why this is the case, suppose a free charge $q$ is moving through the material at a velocity $\mathbf{v}$ in response to external electric or magnetic fields. Now, the total power $P$ dissipated by a single free charge at any instance is just the rate at which the fields do work on the free charge. Since B-fields do no work, we have
$$
P = \frac{dW}{dt} = \mathbf{F} \cdot \mathbf{v} = q \mathbf{E} \cdot \mathbf{v} \ .
$$
Suppose now a distribution $\rho(\mathbf{x})$ of free charge is moving through the material at some flow velocity $\mathbf{v}(\mathbf{x})$. Then the total power dissipated by the entire charge distribution is given by
$$
P = \int d^3\mathbf{x} \ \rho(\mathbf{x}) \mathbf{E}(\mathbf{x}) \cdot \mathbf{v}(\mathbf{x}) \ .
$$
Since the current density is $\mathbf{J} = \rho \mathbf{v}$, this can also be written
$$
\boxed{
P = \int d^3\mathbf{x} \ \mathbf{J}(\mathbf{x}) \cdot \mathbf{E}(\mathbf{x}) 
} \ .
$$
The dot product $\mathbf{J} \cdot \mathbf{E}$ evidently represents the amount of heat generated per unit volume per unit time inside the material.

Now, if the material is *Ohmic*, that is if it obeys Ohm's law, then $\mathbf{J} = \sigma \mathbf{E}$, and so we can also write
$$
P = \sigma \int d^3\mathbf{x} \ |\mathbf{E}(\mathbf{x})|^2 = \frac{1}{\sigma} \int d^3\mathbf{x} \ |\mathbf{J}(\mathbf{x})|^2 \ .
$$
In the special case where we have an Ohmic material with cross-sectional area $A$ and length $L$ hooked up to a voltage source creating a voltage $V$, we know $|\mathbf{E}| = V/L$ and $|\mathbf{J}| = I/A$, in which case we get the more familiar relations
$$
P = IV = \frac{V^2}{R} = I^2R \ .
$$
Of course, we still haven't answered an important question: If energy is being dissipated as heat, how is it we're able to maintain a steady current inside the material? The answer to this is electromotive force, which we'll discuss in the next section.

## Electromotive Force

When a steady current flows across some material, something must be causing that current to flow. Due to Ohmic heating, the free charges making up the current would eventually come to rest if there wasn't some source of power to keep them from doing so. Said differently, there must be some *electromotive force* to maintain the steady current.

### Definition

Suppose we hook up an Ohmic material to some kind of power supply to create a closed circuit. The power supply could be, for instance, a battery or a generator. If we turn on the power supply, an electrostatic E-field gets created, which drives an induced current through the material according to Ohm's law. Said differently, the power supply is the *cause* of the induced current. Each free charge inside the material will feel a total force
$$
\mathbf{F} = \mathbf{F}_s + q \mathbf{E} \ ,
$$
where $\mathbf{F}_s$ is the force generated by the power supply. The work done in moving the free charge around the closed circuit is then
$$
W = \oint \mathbf{F} \cdot d\boldsymbol{\ell} = \oint \mathbf{F}_s \cdot d\boldsymbol{\ell} \ .
$$
Assuming the power supply itself has zero resistivity (or equivalently infinite conductivity), the total force will be zero across the power supply, where $\mathbf{F}_s = -\mathbf{E}$. Assuming the power supply is connected to the circuit via two terminals at points $\mathbf{a}$ and $\mathbf{b}$ on the circuit, and the force $\mathbf{F}_s$ points from $\mathbf{a}$ to $\mathbf{b}$, we then have
$$
W = \oint \mathbf{F}_s \cdot d\boldsymbol{\ell} = -q \int_\mathbf{a}^\mathbf{b} \mathbf{E} \cdot d\boldsymbol{\ell} \ .
$$
That is, the work done by the power supply to move a free charge all the way around the circuit is just the work done by the E-field on the free charge when moving through the power supply. By convention, we divide this work by $q$ and define
$$
\mathcal{E} \equiv -\int_\mathbf{a}^\mathbf{b} \mathbf{E} \cdot d\boldsymbol{\ell} \ .
$$
We call $\mathcal{E}$ the *electromotive force* or *EMF* of the power supply. Since the EMF is the work per unit charge to move a free charge all the way around the circuit, we can think of the EMF itself as the cause of the current. Despite its name, the EMF is actually a *voltage*, not a *force*. It's the potential difference created by the power supply across the rest of the circuit. The entire purpose, if you will, of the power supply, is to establish this potential difference, which then generates a current according to Ohm's law.

FIGURE (show circuit with a power supply and EMF causing a current)

Notice in defining the EMF we've said nothing about the internals of the power supply itself. The source of the EMF could be essentially anything that creates an E-field. If this source is a battery, the EMF is caused by chemical reactions taking place inside the battery. If the source is  a Van de Graaf machine, the EMF is caused by a belt sweeping up free charges and placing them on the circuit directly. If the source is a generator, the EMF is caused by a wire moving through a magnetic field. This last source is the one we'll focus on now. When the source is a generator, we say that the EMF is a *motional EMF*.

### Motional EMF

- Move a wire through a uniform B-field. Force will be a Lorentz force. Show how Faraday's law falls out.

- Redo above section, trying to avoid focusing so much on a fixed circuit with two distinct terminals.
- EMF == The total voltage across the circuit *excluding* the power supply
- Consider briefly mentioning Kirkhoff's rules and maybe doing a couple examples under Ohm's law section (series, parallel?)
  - $\sum V_i = 0$ (follows from a conservative E-field)
  - $I_{in} = I_{out}$ through any node (follows from charge conservation)
  - Series: $R = R_1 + \cdots + R_n$
  - Parallel: $1/R = 1/R_1 + \cdots + 1/R_n$
  - RC Circuit: $V = IR + Q/C$ or $V/R = \dot Q + Q/RC$

## Faraday's Law

In the early 19th century, Faraday studied the behavior of current flowing through an electric circuit. In doing so he accidentally stumbled on one of the most important facts of electromagnetism, that electric and magnetic fields are related. Specifically, Faraday observed that he could measure a brief transient current flowing through a circuit under the following conditions:

- If the steady current in a second nearby circuit is turned on or off.
- If the second circuit is moved relative to the first circuit while a steady current is flowing through it.
- If a bar magnet is thrust into or out of the first circuit.

- If none of these things is taking place, no current is measured to flow through the first circuit.

Faraday interpreted the transient current flow as being due to a changing magnetic flux through the first circuit, with the changing magnetic flux inducing an electric field around the circuit via an *electromotive force*. He called this phenomenon *electromagnetic induction*.

---

Nowadays we interpret Faraday's results mathematically as follows. Suppose a closed circuit is running along some closed loop $\mathcal{C}$ containing a bounded open surface $\mathcal{S}$ with unit normal $\mathbf{n}$. In the background we suppose there is some magnetic field $\mathbf{B}$. Then there will be a magnetic flux $\Phi_B$ through the circuit given by the integral
$$
\Phi_B = \int_\mathcal{S} da \ \mathbf{B} \cdot \mathbf{n} \ .
$$
Suppose an electric field $\mathbf{E}$ is present at each point along the circuit. Then we define the *electromotive force* or *EMF* $\mathcal{E}$ around the circuit as the closed loop integral
$$
\mathcal{E} \equiv \oint_\mathcal{C} \mathbf{E} \cdot d\boldsymbol{\ell} \ .
$$
Notice that despite its name, EMF is not a force. It doesn't even have dimensions of force, but instead dimensions of scalar potential or voltage. The EMF should be thought of as a *source voltage* created across the circuit due to some power source. For instance, if a circuit is hooked up to a battery, the EMF is the source voltage created by the battery itself. If the power source is some changing magnetic field as Faraday suggests, it's the changing magnetic field that creates the EMF.

Faraday's observations can now be expressed mathematically by saying the induced EMF around a circuit is proportional to the time derivative of the magnetic flux through the circuit,
$$
\mathcal{E} = -k \frac{d\Phi_B}{dt} \ .
$$
The proportionality constant $k$ depends only on the choice of units. It is not an empirical constant. From dimensional analysis, it's clear that if we want $\mathbf{E}$ and $\mathbf{B}$ to have the same units then $k$ must have units of inverse velocity. Since the speed of light $c$ is the only characteristic velocity available to us, we choose $k \equiv 1/c$, so that in Gaussian units we have
$$
\boxed{
\mathcal{E} = -\frac{1}{c} \frac{d\Phi_B}{dt}
} \ .
$$
This relation between EMF and magnetic flux is known as *Faraday's Law*.

- Consider first doing sections on Ohm's law and EMF first, similar to Griffiths
- Talk about the sign in Faraday's law, and use Lenz' law as a rule to find the directions
- Lenz' Law: nature abhors a change in (magnetic) flux
- Lenz's law also implies a Lorentz force opposing the motion
- Show how analogy between Ampere and Faraday laws can be used to find E-fields for various problems

## Inductance



## Energy in Magnetic Fields

- Mention quasistatics case, where we assume both E and B fields are time independent
- Mention (mutual) inductance, $\mathcal{E} = -L \dot I$ where $L$ is geometrical (units of Oersted)
- Use Faraday's law to derive energy stored in B-fields, $u = 1/2c \ \mathbf{J} \cdot \mathbf{A} = 1/2 \ \mathbf{B}^2$
- Show how electromagnetic induction (generator) works by an example where circuit is rotated in a constant B-field
- Mention eddy currents, induced currents created in a material passed through a magnetic field to oppose motion



$$
\mathcal{E} = - \frac{1}{c} \frac{\partial \Phi_B}{\partial t}
$$

$$
\nabla \times \mathbf{E} = -\frac{1}{c} \frac{\partial \mathbf{B}}{\partial t}
$$

$$
\mathcal{E} = \frac{L I}{c}
$$





Maxwell's Equations

- State quasistatic field equations
- Introduce the displacement current to maintain charge conservation


$$
\begin{align*}
\nabla \cdot \mathbf{E} &= 4\pi \rho \ , \\
\nabla \times \mathbf{E} &= \frac{1}{c} \frac{\partial \mathbf{B}}{\partial t} \ , \\
\nabla \cdot \mathbf{B} &= 0 \ , \\
\nabla \times \mathbf{B} &= \frac{4\pi}{c} \mathbf{J} - \frac{1}{c} \frac{\partial \mathbf{E}}{\partial t} \ . \\
\end{align*}
$$

$$
\begin{align*}
\mathbf{E} &= -\nabla\phi + \frac{1}{c} \frac{\partial \mathbf{A}}{\partial t} \ , \\
\mathbf{B} &= \nabla \cdot \mathbf{A} \ .
\end{align*}
$$


$$
\frac{\partial \rho}{\partial t} + \nabla \cdot \mathbf{J} = 0 \ .
$$
