# Advanced Methods III

In this chapter, we continue on with the topic of advanced methods in electrostatics by continuing to look at advanced techniques for solving electrostatics problems. We'll first introduce the multipole expansion, a useful approach for finding approximate solutions to an electrostatics problem when we're far away from the source charges. Once we've done that, we'll discuss the mathematical topic of complex analysis, deriving important results like conformal mappings and the residue theorem. Finally, we'll apply the idea of conformal mappings to show how it can be used to solve electrostatics problems in two dimensions.

## Multipole Expansion

- derive the multipole expansion for cartesian coordinates, defining the various moments involved
- derive the multipole expansion for spherical coordinates and show it's equivalent to the former
- work a few examples (see Griffiths mostly, maybe Jackson)

## Complex Analysis

- Keep a shorter topic on complex variables in the preliminaries.
- Move the more advanced stuff to this section and provide more details and examples.



## Conformal Mappings

- contour methods are a powerful method for solving 2D electrostatics problems
- idea is to use contour mappings from complex analysis to turn an electrostatics problem into a complex analysis problem
- you've already shown that a complex function satisfies Laplace's equation, now show what conformal mappings are
- work a few examples (see Greiner)