project:
  type: book
  output-dir: docs

book:
  title: "Personal Notes"
  author: "Ryan Kingery"
  # date: "2/12/2023"
  page-navigation: true
  sidebar:
    style: docked
    background: light
    collapse-level: 3
  chapters:
    - index.qmd
    - part: "Classical Mechanics" # classical-mechanics/classical-mechanics.qmd
      chapters:
        - classical-mechanics/newtonian-mechanics.qmd
        - classical-mechanics/simple-systems.qmd
        - classical-mechanics/reference-frames.qmd
        - classical-mechanics/lagrangian-mechanics.qmd
        - classical-mechanics/hamiltonian-mechanics.qmd
        - classical-mechanics/central-forces.qmd
        - classical-mechanics/coupled-oscillations.qmd
        - classical-mechanics/rigid-bodies.qmd
        - classical-mechanics/canonical-transformations.qmd
        - classical-mechanics/integrability-and-chaos.qmd
        - classical-mechanics/continuum-mechanics.qmd
    - part: "Electromagnetism" #electrodynamics/electrodynamics.qmd
      chapters:
        - electrodynamics/preliminaries.qmd
        - electrodynamics/electrostatics.qmd
        - electrodynamics/bvps-1.qmd
        - electrodynamics/bvps-2.qmd
        - electrodynamics/multipole-expansion.qmd
        - electrodynamics/magnetostatics.qmd
        - electrodynamics/circuits-and-emf.qmd
        - electrodynamics/electrodynamics.qmd
        - electrodynamics/potentials.qmd
        - electrodynamics/orthogonal-functions.qmd
        - electrodynamics/complex-analysis.qmd
    - part: "Circuit Analysis" # circuits/circuits.qmd
      chapters:
        - circuits/circuit-abstraction.qmd
        - circuits/analysis.qmd
        - circuits/nonlinear-methods.qmd
        - circuits/digital-abstraction.qmd
        - circuits/amplifiers.qmd
        - circuits/first-order-systems.qmd
        - circuits/second-order-systems.qmd
        - circuits/ac-analysis.qmd
        - circuits/op-amps.qmd
        - circuits/energy-power.qmd
    - part: "Quantum Mechanics" # quantum-mechanics/quantum-mechanics.qmd
      chapters:
        - quantum-mechanics/identical-particles.qmd
        - quantum-mechanics/second-quantization.qmd
    - part: "Statistical Mechanics" # statistical-mechanics/statistical-mechanics.qmd
      chapters:
        - statistical-mechanics/thermodynamics.qmd
        - statistical-mechanics/probability.qmd
        - statistical-mechanics/kinetic-theory.qmd
        - statistical-mechanics/classical-stat-mech.qmd
        - statistical-mechanics/classical-gases.qmd
        - statistical-mechanics/quantum-stat-mech.qmd
        - statistical-mechanics/quantum-gases.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
    fig-align: center
  # pdf:
  #   documentclass: scrreprt



